version: '3.9'
services:
  app:
    container_name: golang_container
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - DATABASE_HOST=postgres_container # Connect to the Postgres container using its name for docker-compose
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clarified_file_manager_db
    tty: true # teletypewriter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${SERVER_PORT}:8080' # Host:Container
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - learning

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clarified_file_manager_db
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - learning

volumes:
  pg_data:

# Networks to be created to facilitate communication between containers
networks:
  learning:
    driver: bridge
