= ASVS Security Testing
:sectnums:
:sectnumlevels: 5

== Selected ASVS points

[cols="1,2,4", options="header"]
|===
| ID | Type | Description

| 3.3.1
| Session Management
| Verify that logout and expiration invalidate the session token, such that the back button or a downstream relying party does not resume an authenticated session, including across relying parties.

| 5.3.4
| Server-Side Attacks
| Verify that data selection or database queries (e.g., SQL, HQL, ORM, NoSQL) use parameterized queries, ORMs, entity frameworks, or are otherwise protected from database injection attacks. 

| 12.5.2
| XSS
| Verify that direct requests to uploaded files will never be executed as HTML/JavaScript content.

| 13.2.3
| REST/API
| Verify that RESTful web services that utilize cookies are protected from Cross-Site Request Forgery via the use of at least one or more of the following: double submit cookie pattern, CSRF nonces, or Origin request header checks.

| 12.1.1
| File Management
| Verify that the application will not accept large files that could fill up storage or cause a denial of service.

|===

== Tests

=== Session Management: https://asvs.dev/v4.0.3/0x12-V3-Session-management/#v33-session-termination[3.3.1]

Verify that logout and expiration invalidate the session token, such that the back button or a downstream relying party does not resume an authenticated session, including across relying parties.

==== Prerequisites

. User has a valid account.

==== Procedure

===== User logs in to the webpage and receives a session cookie

[source, HTTP]
.Http POST /login request
----
POST /login HTTP/1.1
Host: 0.0.0.0:8070
Cookie: session=MTczMzg1Njg1MXxEWDhFQVFMX2dBQUJFQUVRQUFBZ180QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQVZwYm5Rek1nUUNBQlE9fGbIg1uNiY6rB-pDYFo8A832HwpJsuI0pH5BrW9oWXy6
Content-Length: 224
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"

x
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

x
------WebKitFormBoundary7MA4YWxkTrZu0gW--
----

[source, HTTP]
.HTTP POST /login response headers
----
HTTP/1.1 200 OK
Hx-Redirect: /files
Set-Cookie: session=MTczMzg1ODc4OXxEWDhFQVFMX2dBQUJFQUVRQUFBZ180QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQVZwYm5Rek1nUUNBQlE9fG44koPjnQRtRSe-mDLdCqHpx0DUoEazPgcKVohUz6Tj; Expires=Tue, 10 Dec 2024 20:26:29 GMT; Max-Age=3600; HttpOnly; SameSite=Lax
Date: Tue, 10 Dec 2024 19:26:29 GMT
Content-Length: 1803
Content-Type: text/html; charset=utf-8
----

===== User logs out of the webpage

[source, HTTP]
.HTTP GET /logout request
----
GET /logout HTTP/1.1
Host: 0.0.0.0:8070
Cookie: session=MTczMzg1ODc4OXxEWDhFQVFMX2dBQUJFQUVRQUFBZ180QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQVZwYm5Rek1nUUNBQlE9fG44koPjnQRtRSe-mDLdCqHpx0DUoEazPgcKVohUz6Tj; session=MTczMzg1ODkwOHxEWDhFQVFMX2dBQUJFQUVRQUFBWF80QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQUE9fHMbiidDTt7Y4T_tpG0ISx2rXwNfjQeU39enikQCVxEG
----

[source, HTTP]
.HTTP GET /logout response
----
HTTP/1.1 303
Content-Type: text/html; charset=utf-8
Location: /login
Set-Cookie: session=MTczMzg1ODkwOHxEWDhFQVFMX2dBQUJFQUVRQUFBWF80QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQUE9fHMbiidDTt7Y4T_tpG0ISx2rXwNfjQeU39enikQCVxEG; Expires=Tue, 10 Dec 2024 20:28:28 GMT; Max-Age=3600; HttpOnly; SameSite=Lax
Date: Tue, 10 Dec 2024 19:28:28 GMT
Content-Length: 33
----

===== User makes GET /files request with previous session cookie

[source, HTTP]
.HTTP GET /files request
----
GET /files HTTP/1.1
Host: 0.0.0.0:8070
Cookie: session=MTczMzg1ODc4OXxEWDhFQVFMX2dBQUJFQUVRQUFBZ180QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQVZwYm5Rek1nUUNBQlE9fG44koPjnQRtRSe-mDLdCqHpx0DUoEazPgcKVohUz6Tj; session=MTczMzg1ODkwOHxEWDhFQVFMX2dBQUJFQUVRQUFBWF80QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQUE9fHMbiidDTt7Y4T_tpG0ISx2rXwNfjQeU39enikQCVxEG
----

[source, HTTP]
.HTTP GET /files response headers
----
HTTP/1.1 200 OK
Date: Tue, 10 Dec 2024 19:45:54 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
----

[source, HTML]
.HTML GET /files response 
----
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://unpkg.com/htmx.org@1.9.12"></script>
<link rel="stylesheet" href="/static/css/styles.css" />
<title>Clarified-file-manager</title>
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
<div class="container-fluid">
<a class="navbar-brand">Clarified-file-manager</a>
<ul class="navbar-nav mb-1 mb-lg-0 d-flex">
<li class="nav-item">
<a class="nav-link active" aria-current="page" href="/logout">Log out</a>
</li>
</ul>
</div>
</nav>
<div class="row">
<div class="p-5 mt-5">
<h4>Upload File</h4>
<form
id="upload-form"
class="form"
hx-post="/files"
hx-encoding="multipart/form-data"
hx-target="#upload-form"
hx-swap="outerHTML"
>
<div class="input-group">
<input type="file" class="form-control" name="file" required>
<button class="btn btn-primary" type="submit">Upload</button>
</div>
</form>
<h4 class="mt-3">Uploaded Files</h4>
<table id="files-table" class="table table-striped mt-3">
<thead>
<tr>
<th>
<a href="/files?sort=name&amp;dir=asc" hx-target="#files-table" hx-get="/files?sort=name&amp;dir=asc" hx-push-url="true">
Name
</a>
</th>
<th>
<a href="/files?sort=mime_type&amp;dir=asc" hx-target="#files-table" hx-get="/files?sort=mime_type&amp;dir=asc" hx-push-url="true">
Mime Type
</a>
</th>
<th>
<a href="/files?sort=size&amp;dir=asc" hx-target="#files-table" hx-get="/files?sort=size&amp;dir=asc" hx-push-url="true">
Size
</a>
</th>
<th>
<a href="/files?sort=uploaded_at&amp;dir=asc" hx-target="#files-table" hx-get="/files?sort=uploaded_at&amp;dir=asc" hx-push-url="true">
Uploaded At <i class="fa-solid fa-sort-down"></i>
</a>
</th>
</tr>
</thead>
<tbody id="files-list" hx-get="/files?sort=uploaded_at&dir=desc" hx-trigger="file-uploaded from:body">
</tbody>
</table>
</div>
</div>
</body>
</html>
----

==== Result(s)

The user is incorrectly logged in and authenticated, allowing them to perform all user actions.

==== Explanation

Terminating a session does not invalidate the current and other active session tokens, which remain valid until their MaxValue expiration time.

==== Threat analysis

If a malicious actor gains access to the session token, they can continue using the session even after the user has logged out, until the session token expires (MaxValue).

The malicious actor can perform the following actions:

. View the list of all files uploaded by the user.
. Download any file from the user's account.
. Upload new files to the user's account.
. Delete any file from the user's account.

==== Recommendations

. Invalidate the session token on logout.

=== Server-Side Attacks: https://asvs.dev/v4.0.3/0x13-V5-Validation-Sanitization-Encoding/#v53-output-encoding-and-injection-prevention[5.3.4]

Verify that data selection or database queries (e.g., SQL, HQL, ORM, NoSQL) use parameterized queries, ORMs, entity frameworks, or are otherwise protected from database injection attacks.

==== Prerequisites
. User has a valid account.
. User is logged in.

==== Procedure

Our analysis detected 2 SQL injection vulnerabilities in the application. 

===== Vulnerable download file request

Download file request is vulnerable to SQL injection and allows to download any file without authentication.

[source, HTTP]
.HTTP GET /files/1 OR '1'='1' ORDER BY name LIMIT 1 OFFSET 1;--" request header
----
GET /files/1 OR '1'='1' ORDER BY name LIMIT 1 OFFSET 1;-- HTTP/1.1
Host: 0.0.0.0:8070
Cookie: session=MTczNDM3OTc1NXxEWDhFQVFMX2dBQUJFQUVRQUFBZ180QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQVZwYm5Rek1nUUNBQlE9fOEFU2YXZiKWD9CBaEhdvcjurMOkUCbfGHv-Pw8pwUYX
----

[source, HTTP]
.HTTP GET /files/1 OR '1'='1' ORDER BY name LIMIT 1 OFFSET 1;--" response header
----
HTTP/1.1 200 OK
Content-Disposition: attachment; filename="5433.612000.jpg"
Content-Type: image/jpeg
Date: Mon, 16 Dec 2024 20:09:27 GMT
Transfer-Encoding: chunked
----

====== Threat analysis

. Malicious actor can download any file from the database without authentication.

===== Vulnerable table sorting

Table sorting is not enumerated and is vulnerable to SQL injection. This can be exploited to perform DoS attacks.

[source, HTTP]
.HTTP GET /files?sort=name, (SELECT 1 FROM pg_sleep(30)) request
----
GET /files?sort=name, (SELECT 1 FROM pg_sleep(30)) HTTP/1.1
Host: 0.0.0.0:8070
Cookie: session=MTczNDM3OTc1NXxEWDhFQVFMX2dBQUJFQUVRQUFBZ180QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQVZwYm5Rek1nUUNBQlE9fOEFU2YXZiKWD9CBaEhdvcjurMOkUCbfGHv-Pw8pwUYX
----

Request took `30.04 seconds` to respond.


[source, HTTP]
.HTTP GET /files?sort=name, (SELECT 1 FROM pg_sleep(30)) response
----
HTTP/1.1 200 OK
Date: Mon, 16 Dec 2024 20:11:43 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
----

====== Threat analysis

. Malicious actor can use this vulnerability to perform DoS attacks.

===== Explanation

Parameterized queries protect against SQL injection by ensuring that user input is treated strictly as data, not as part of the SQL query itself. This prevents malicious users from manipulating the SQL query structure to execute unintended commands. Query that downloads the file is not parametrized and is vulnerable to SQL injection.

===== Recommendations

. Parametrize all queries to prevent SQL injection attacks.

=== XSS: https://asvs.dev/v4.0.3/0x20-V12-Files-Resources/#v125-file-download[12.5.2]

Verify that direct requests to uploaded files will never be executed as HTML/JavaScript content.

==== Prerequisites

. User has a valid account.
. User is logged in.

==== Procedure

. Create file with content 
```html
<script>
  alert('XSS');
</script>
```
name it `malicious.html`.

. Upload file to the webpage.
. Download file from the webpage.
. Inspect if alert message was executed.

[source, HTTP]
.HTTP GET /files/{file_id} request
----
GET /files/41 HTTP/1.1
Host: 0.0.0.0:8070
Cookie: session=MTczNDM3OTc1NXxEWDhFQVFMX2dBQUJFQUVRQUFBZ180QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQVZwYm5Rek1nUUNBQlE9fOEFU2YXZiKWD9CBaEhdvcjurMOkUCbfGHv-Pw8pwUYX
----

[source, HTTP]
.HTTP GET /files/{file_id} response headers
----
HTTP/1.1 200 OK
Content-Disposition: inline; filename="malicious.html"
Content-Type: text/html
Date: Mon, 16 Dec 2024 20:14:08 GMT
Content-Length: 31
----

[source, HTML]
.HTML GET /files/{file_id} response
----
<script>alert('XSS');</script>
----

==== Expected behaviour

Javascript code is not executed. Alert message is not displayed.

==== Result(s)

Javascript code is executed. Alert message is displayed.

==== Explanation

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition[Content-Disposition] header is set to inline, which allows the browser to render the file as HTML/JavaScript content.

==== Threat analysis

. Arbitrary JavaScript code can be executed if the file is rendered as HTML/JavaScript content in the browser on download.

This threat is especially dangerous together with CSRF attack vulnerability when malicious actor can upload a file with malicious content. When user downloads the file, the malicious code is executed. If the application coockie setting is httpOnly=false, the malicious actor can steal the user's session cookie and hijack the user's session. 

==== Recommendations

. Set `Content-Disposition: attachment` header to force the browser to download the file instead of displaying it inline.
. Whitelist allowed MIME types.
. Discard files with unexpected file content.
. Set `X-Content-Type-Options: nosniff` header. Some browsers may perform MIME sniffing and ignore the Content-Type header if the `X-Content-Type-Options: nosniff` header is not set. If nosniff is not set, the browser may sniff the content of the files and treat files with incorrect mime-type/extension as HTML/JavaScript, potentially executing malicious script.
. Scan file content with antivirus scanner before uploading it to the server.

=== REST/API: https://asvs.dev/v4.0.3/0x21-V13-API/#v132-restful-web-service[13.2.3]

Verify that RESTful web services that utilize cookies are protected from Cross-Site Request Forgery via the use of at least one or more of the following: double submit cookie pattern, CSRF nonces, or Origin request header checks.


==== Prerequisites
. User has a valid account.
. User is logged in.

==== Procedure

===== OPTIONS request to check if DELETE request is allowed

[source, HTTP]
.HTTP OPTIONS /files/{file_id} request
----
OPTIONS /files/40 HTTP/1.1
Host: 0.0.0.0:8070
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Access-Control-Request-Method: DELETE
Referer: http://0.0.0.0:8000/
Origin: http://0.0.0.0:8000
Connection: keep-alive
Priority: u=4
----

[source, HTTP]
.HTTP OPTIONS /files/{file_id} response
----
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, PUT, DELETE
Access-Control-Allow-Origin: http://0.0.0.0:8000
Date: Mon, 16 Dec 2024 17:22:45 GMT
Content-Length: 0
----

===== DELETE request to delete a file

[source, HTTP]
.HTTP DELETE /files/{file_id} request
----
DELETE /files/40 HTTP/1.1
Host: 0.0.0.0:8070
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://0.0.0.0:8000/
Origin: http://0.0.0.0:8000
Connection: keep-alive
Cookie: session=MTczNDM2ODc2NHxEWDhFQVFMX2dBQUJFQUVRQUFBZ180QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQVZwYm5Rek1nUUNBQlE9fABUsoDAXSwtYR0bwg9496lirdXpmqgHZ8KqJUkA3Zur
Priority: u=0
----

[source, HTTP]
.HTTP DELETE /files/{file_id} response
----
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, PUT, DELETE
Access-Control-Allow-Origin: http://0.0.0.0:8000
Date: Mon, 16 Dec 2024 17:22:45 GMT
Content-Length: 0
----

==== Expected behaviour

Options request returns `405 Method not allowed` status code if the state changing requests are being run from different origin (http://0.0.0.0:8000) from the host (http://0.0.0.0:8070) and DELETE request will not be run.

[source, HTTP]
.HTTP OPTIONS /files/{file_id} response
----
HTTP/1.1 405 Method Not Allowed
Date: Mon, 16 Dec 2024 14:13:24 GMT
Content-Length: 0
----

==== Result(s)

GET, POST, PUT and DELETE methods are vulnerable to CSRF attacks.

==== Explanation

When doing CORS requests, server makes preflight OPTIONS request to check if the request is allowed. If the request is not allowed, the server will respond to the OPTIONS request with `405 Method Not Allowed`. 

==== Threat analysis

Malicios actor can perform CSRF attacks to a logged in user by sending a DELETE, POST, PUT or GET request to the server.

This results in the following actions:

. Delete any file from the user's account.
. Upload new files to the user's account.
. Download any file from the user's account.
. View the list of all files uploaded by the user.

==== Recommendations

. Whitelist allowed origins. Do not allow requests from any origin.
. Obfuscate file ids to mitigate CSRF attacks that download or delete files.

=== Files: https://asvs.dev/v4.0.3/0x20-V12-Files-Resources/#control-objective[12.1.1]

Verify that the application will not accept large files that could fill up storage or cause a denial of service.

==== Prerequisites

. User has a valid account.
. User is logged in.

==== Procedure

===== Upload file larger than 1 GB

[source, HTTP]
.HTTP POST /files request
----
POST /files HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,et;q=0.8
Connection: keep-alive
Content-Length: 5578801484
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary2psQU20XsR5HqUxo
Cookie: session=MTczNDM3NzYzNnxEWDhFQVFMX2dBQUJFQUVRQUFBZ180QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQVZwYm5Rek1nUUNBQlE9fBbvpS0GhLfEv4i12beIheuJLdrcS_0TW4mDHRdMSV8K
HX-Current-URL: http://0.0.0.0:8070/files
HX-Request: true
HX-Target: upload-form
HX-Trigger: upload-form
Host: 0.0.0.0:8070
Origin: http://0.0.0.0:8070
Referer: http://0.0.0.0:8070/files
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
----

[source, HTTP]
.HTTP POST /files response headers
----
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, PUT, DELETE
Access-Control-Allow-Origin: http://0.0.0.0:8070
Date: Mon, 16 Dec 2024 19:48:01 GMT
Content-Length: 476
Content-Type: text/plain; charset=utf-8
----

[source, HTML]
.HTML POST /files response 
----
<form
    id="upload-form"
    class="form" 
    hx-post="/files" 
    hx-encoding="multipart/form-data"
    hx-target="#upload-form"
    hx-swap="outerHTML"
>
    <div class="input-group">
        <input type="file" class="form-control" name="file" required>
        <button class="btn btn-primary" type="submit">Upload</button>
    </div>

    
    <div class="alert alert-danger mt-3" role="alert">
        File size exceeds the 10 MiB limit
    </div>
</form>
----

===== Upload file smaller than 1 GB

[source, HTTP]
.HTTP POST /files request
----
POST /files HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,et;q=0.8
Connection: keep-alive
Content-Length: 175179
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarysLwUmJMwR6Ef1UQE
Cookie: session=MTczNDM3NzYzNnxEWDhFQVFMX2dBQUJFQUVRQUFBZ180QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQVZwYm5Rek1nUUNBQlE9fBbvpS0GhLfEv4i12beIheuJLdrcS_0TW4mDHRdMSV8K
HX-Current-URL: http://0.0.0.0:8070/files
HX-Request: true
HX-Target: upload-form
HX-Trigger: upload-form
Host: 0.0.0.0:8070
Origin: http://0.0.0.0:8070
Referer: http://0.0.0.0:8070/files
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
----

[source, HTTP]
.HTTP POST /files response headers
----
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, PUT, DELETE
Access-Control-Allow-Origin: http://0.0.0.0:8070
Hx-Trigger: file-uploaded
Date: Mon, 16 Dec 2024 19:50:44 GMT
Content-Length: 479
Content-Type: text/plain; charset=utf-8
----

[source, HTML]
.HTML POST /files response 
----
<form
    id="upload-form"
    class="form" 
    hx-post="/files" 
    hx-encoding="multipart/form-data"
    hx-target="#upload-form"
    hx-swap="outerHTML"
>
    <div class="input-group">
        <input type="file" class="form-control" name="file" required>
        <button class="btn btn-primary" type="submit">Upload</button>
    </div>

    

    
    <div class="alert alert-success mt-3" role="alert">
        File has been successfully uploaded.
    </div>
    
</form>
----
==== Expected behaviour

File larger than 1 GB is not uploaded.

==== Result(s)

File larger than 1 GB is not uploaded. UI diplays a message: "File size exceeds the 10 MiB limit", however upload request returned 200 OK status code.

==== Explanation

Source code https://github.com/gretelilijane/clarified-file-manager/blob/0e106ae1dda9b31e08814458a7dbc1f1ea2bf9e9/handlers/uploadHandler.go#L41[checks if the file size is larger than 10 MiB] and if it is, it does not save the file to PostgreSQL.

==== Threat analysis

N/A

==== Recommendations

. Return `413 Payload Too Large` status code when file size exceeds the limit.
