= ASVS Security Testing
:sectnumlevels: 5

== Selected ASVS points

[cols="1,1,1", options="header"]
|===
| Type | ID | Description

| 3.3.1
| Session Management
| Verify that logout and expiration invalidate the session token, such that the back button or a downstream relying party does not resume an authenticated session, including across relying parties.

| 5.3.4
| Server-Side Attacks
| Verify that data selection or database queries (e.g., SQL, HQL, ORM, NoSQL) use parameterized queries, ORMs, entity frameworks, or are otherwise protected from database injection attacks. 

| 12.5.2
| XSS
| Verify that direct requests to uploaded files will never be executed as HTML/JavaScript content.

| 13.2.3
| REST/API
| Verify that RESTful web services that utilize cookies are protected from Cross-Site Request Forgery via the use of at least one or more of the following: double submit cookie pattern, CSRF nonces, or Origin request header checks.

| TODO
| File Management
| TODO

|===

== Tests

=== https://asvs.dev/v4.0.3/0x12-V3-Session-management/#v33-session-termination[3.3.1] Session Management

Verify that logout and expiration invalidate the session token, such that the back button or a downstream relying party does not resume an authenticated session, including across relying parties.

==== Prerequisites

===== User has a valid account

[source,http]
.Http /signup POST request
----
POST /signup HTTP/1.1
Host: 0.0.0.0:8070
Content-Length: 323
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"

x
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

x
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="confirm_password"

x
------WebKitFormBoundary7MA4YWxkTrZu0gW--
----

===== User logs in to the webpage and receives a session cookie

[source,http]
.Http /login POST request
----
POST /login HTTP/1.1
Host: 0.0.0.0:8070
Cookie: session=MTczMzg1Njg1MXxEWDhFQVFMX2dBQUJFQUVRQUFBZ180QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQVZwYm5Rek1nUUNBQlE9fGbIg1uNiY6rB-pDYFo8A832HwpJsuI0pH5BrW9oWXy6
Content-Length: 224
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"

x
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

x
------WebKitFormBoundary7MA4YWxkTrZu0gW--
----

[source,http]
.Http response (without body)
----
HTTP/1.1 200 OK
Hx-Redirect: /files
Set-Cookie: session=MTczMzg1ODc4OXxEWDhFQVFMX2dBQUJFQUVRQUFBZ180QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQVZwYm5Rek1nUUNBQlE9fG44koPjnQRtRSe-mDLdCqHpx0DUoEazPgcKVohUz6Tj; Expires=Tue, 10 Dec 2024 20:26:29 GMT; Max-Age=3600; HttpOnly; SameSite=Lax
Date: Tue, 10 Dec 2024 19:26:29 GMT
Content-Length: 1803
Content-Type: text/html; charset=utf-8
----

==== Procedure

===== User logs out of the webpage
Http request:
```http
GET /logout HTTP/1.1
Host: 0.0.0.0:8070
Cookie: session=MTczMzg1ODc4OXxEWDhFQVFMX2dBQUJFQUVRQUFBZ180QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQVZwYm5Rek1nUUNBQlE9fG44koPjnQRtRSe-mDLdCqHpx0DUoEazPgcKVohUz6Tj; session=MTczMzg1ODkwOHxEWDhFQVFMX2dBQUJFQUVRQUFBWF80QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQUE9fHMbiidDTt7Y4T_tpG0ISx2rXwNfjQeU39enikQCVxEG
```

Http response headers:
```http
HTTP/1.1 303
Content-Type: text/html; charset=utf-8
Location: /login
Set-Cookie: session=MTczMzg1ODkwOHxEWDhFQVFMX2dBQUJFQUVRQUFBWF80QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQUE9fHMbiidDTt7Y4T_tpG0ISx2rXwNfjQeU39enikQCVxEG; Expires=Tue, 10 Dec 2024 20:28:28 GMT; Max-Age=3600; HttpOnly; SameSite=Lax
Date: Tue, 10 Dec 2024 19:28:28 GMT
Content-Length: 33
```

===== User makes GET /files request with previous session cookie

Http request:
```http
GET /files HTTP/1.1
Host: 0.0.0.0:8070
Cookie: session=MTczMzg1ODc4OXxEWDhFQVFMX2dBQUJFQUVRQUFBZ180QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQVZwYm5Rek1nUUNBQlE9fG44koPjnQRtRSe-mDLdCqHpx0DUoEazPgcKVohUz6Tj; session=MTczMzg1ODkwOHxEWDhFQVFMX2dBQUJFQUVRQUFBWF80QUFBUVp6ZEhKcGJtY01DUUFIZFhObGNsOXBaQUE9fHMbiidDTt7Y4T_tpG0ISx2rXwNfjQeU39enikQCVxEG
```

Http response:
```http
HTTP/1.1 200 OK
Date: Tue, 10 Dec 2024 19:45:54 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://unpkg.com/htmx.org@1.9.12"></script>
<link rel="stylesheet" href="/static/css/styles.css" />
<title>Clarified-file-manager</title>
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
<div class="container-fluid">
<a class="navbar-brand">Clarified-file-manager</a>
<ul class="navbar-nav mb-1 mb-lg-0 d-flex">
<li class="nav-item">
<a class="nav-link active" aria-current="page" href="/logout">Log out</a>
</li>
</ul>
</div>
</nav>
<div class="row">
<div class="p-5 mt-5">
<h4>Upload File</h4>
<form
id="upload-form"
class="form"
hx-post="/files"
hx-encoding="multipart/form-data"
hx-target="#upload-form"
hx-swap="outerHTML"
>
<div class="input-group">
<input type="file" class="form-control" name="file" required>
<button class="btn btn-primary" type="submit">Upload</button>
</div>
</form>
<h4 class="mt-3">Uploaded Files</h4>
<table id="files-table" class="table table-striped mt-3">
<thead>
<tr>
<th>
<a href="/files?sort=name&amp;dir=asc" hx-target="#files-table" hx-get="/files?sort=name&amp;dir=asc" hx-push-url="true">
Name
</a>
</th>
<th>
<a href="/files?sort=mime_type&amp;dir=asc" hx-target="#files-table" hx-get="/files?sort=mime_type&amp;dir=asc" hx-push-url="true">
Mime Type
</a>
</th>
<th>
<a href="/files?sort=size&amp;dir=asc" hx-target="#files-table" hx-get="/files?sort=size&amp;dir=asc" hx-push-url="true">
Size
</a>
</th>
<th>
<a href="/files?sort=uploaded_at&amp;dir=asc" hx-target="#files-table" hx-get="/files?sort=uploaded_at&amp;dir=asc" hx-push-url="true">
Uploaded At <i class="fa-solid fa-sort-down"></i>
</a>
</th>
</tr>
</thead>
<tbody id="files-list" hx-get="/files?sort=uploaded_at&dir=desc" hx-trigger="file-uploaded from:body">
</tbody>
</table>
</div>
</div>
</body>
</html>
```

==== Result(s)

The user is incorrectly logged in and authenticated, allowing them to perform all user actions.

==== Explanation

Terminating a session does not invalidate the session token, which remains valid until its MaxValue expiration time.

==== Threat analysis

If a malicious actor gains access to the session token, they can continue using the session even after the user has logged out, until the session token expires (MaxValue).

The malicious actor can perform the following actions:

. View the list of all files uploaded by the user.
. Download any file from the user's account.
. Upload new files to the user's account.
. Delete any file from the user's account.

==== Recommendations

. Invalidate the session token on logout.